services:
  mysql:
    image: mysql:5.7
    container_name: p2-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: isla_transfers
      MYSQL_USER: dgago
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./UOC_transfers-1-1.sql:/docker-entrypoint-initdb.d/UOC_transfers-1-1.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: p2-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234

volumes:
  mysql_data: